#!/bin/bash
# Edit production/field-map defaults at the top of generatorScript.py.
# Preview: ./generatorScript.sh /path/to/filtered/inputs
# Submit:  ./generatorScript.sh /path/to/filtered/inputs --submit
# Test:    ./generatorScript.sh /path/to/filtered/inputs --test --submit
# Generate in the job's local $PWD/generator_output, then copy ROOT files to EOS.
# Input layout: PROD_DATE/JOB_NUMBER/SUBJOB_NUMBER/muonDis_*.root.
# Destination: PROD_DATE/generated by default (created after simulation).
# Files: {sim,params,geo}_generatedMuDIS_JOB_NUMBER_SUBJOB_NUMBER.root.
# Set OUTPUT_DIR in generatorScript.py or override with --output-dir /eos/PATH.
set -euo pipefail
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
exec python3 "$script_dir/generatorScript.py" "$@"
